highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jojotenya.github.io
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: CHENG-HAO's Site 
name: C.H. HO 
first_name: CHENG-HAO 
sur_name: HO 
email: jojotenya@gamil.com
email_full: mailto:jojotenya@gamil.com
website: jojoteny.github.io
website_full: https://jojotenya.github.io
github: jojotenya 
linkedin: chho 
#twitter: twitter
tel: +886 955 556995 
tel_full: tel:+886955556995
#google_maps: 'https://www.google.com/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
#address:
#  street: 44 Perth Street
#  postcode: EH3 5BL
#  city: Edinburgh
#  country: United Kingdom
#google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
